Additional storage options
moreonion/webform_prefill pull request #4
Opened 2018-08-22 12:38 UTC by katzmo

* Choose between sessionStorage, localStorage or cookies
* Set expiration for cookies

Depends on https://github.com/moreonion/jquery.formprefill/pull/2

2018-09-03 09:57 UTC, torotil requested changes
… and please allow for multiple enabled storage backends (as does the jQuery plugin).

2018-09-03 09:57 UTC, torotil commented on webform_prefill.module
> - * Implements hook_form_FORM_ID_alter().
Coding-style would be `Implements hook_form_FORM_ID_alter() for webform_client_form().`

2018-09-04 11:29 UTC, torotil approved these changes

2018-09-04 11:30 UTC, torotil commented
Have you tested that this still works after you’ve modified the value in the variables interface?

2018-09-04 13:53 UTC, katzmo commented
Now the `webform_prefill_storage` variable should work with strings and arrays and variable_admin.

2018-09-05 13:54 UTC, merged